apiVersion: v1
kind: ConfigMap
metadata:
  name: ddclient-config
  labels:
    app: dindns
data:
  ddclient: |
    daemon=60
    syslog=yes
    mail=root
    mail-failure=root
    pid=/var/run/ddclient.pid
    ssl=yes                                 
    use=web, web=checkip.dynu.com/, web-skip='IP Address'          
    server=api.dynu.com
    login=
    password=
    protocol=dyndns2
    ***aqui va tu dominio***
