apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnsexit
  labels:
    app: dnsexit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dnsexit
  template:
    metadata:
      labels:
        app: dnsexit
    spec:
      nodeSelector:
        rpi: version3
      containers:
      - name: trinity
        image: valgonzalez/dnsexit
        env:
                - name: LOGIN
                  valueFrom:
                    secretKeyRef:
                      name: trinity
                      key: login
                - name: PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: trinity
                      key: password
                - name: HOST
                  valueFrom:
                    secretKeyRef:
                      name: trinity
                      key: host
                - name: INTERVAL
                  valueFrom:
                    secretKeyRef:
                      name: trinity
                      key: interval
                - name: TZ
                  valueFrom:
                    secretKeyRef:
                      name: trinity
                      key: tz
