# cambia las variables con envsubst utilizando las variables locales:
# ejecuta envsubst < trinity-secret.yaml > trinity-secret-apply.yaml
apiVersion: v1
kind: Secret
metadata:
  name: trinity
type: Opaque
stringData:
  login: "$LOGIN"
  password: "$PASSWORD"
  host: "$HOST"
  interval: "$INTERVAL"
  tz: "$TZ"
